branches:
    only:
        - master
langauge: node_js
node_js:
    - '12.16.1'
install:
    - npm install
script:
    - CI=false npm run build
after_success:
    - firebase hosting:channel:deploy master-preview --token "$FIREBASE_TOKEN"
